package de.comicdb.comicdbcore;

import javax.swing.JPanel;
import javax.swing.SpinnerNumberModel;
import org.openide.util.NbBundle;

public final class ComicWizardVisualPanel extends JPanel {
    
    public static String NAME = "name";
    public static String NR   = "nr";
    
    private ComicWizardBean bean = null;
    /** Creates new form ComicWizardVisualPanel1 */
    public ComicWizardVisualPanel() {
        initComponents();
    }
    
    public String getName() {
        return NbBundle.getMessage(ComicWizardVisualPanel.class, "WIZ_Comic_Name");
    }
    
    public void setComicName(String name) {
        jTextFieldName.setText(name);
    }
    
    public String getComicName() {
        return jTextFieldName.getText();
    }
    
    public Boolean isOneComicSelected() {
        return new Boolean(jRadioButtonOneComic.isSelected());
    }
    
    public Number getNr() {
        return ((SpinnerNumberModel)jSpinnerNr.getModel()).getNumber();
    }
    
    public Number getFrom() {
        return ((SpinnerNumberModel)jSpinnerNrFrom.getModel()).getNumber();
    }
    
    public Number getTo() {
        return ((SpinnerNumberModel)jSpinnerNrTo.getModel()).getNumber();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextFieldName = new javax.swing.JTextField();
        jLabelName = new javax.swing.JLabel();
        jRadioButtonMoreComic = new javax.swing.JRadioButton();
        jRadioButtonOneComic = new javax.swing.JRadioButton();
        jSpinnerNr = new javax.swing.JSpinner();
        jLabelNr = new javax.swing.JLabel();
        jSpinnerNrFrom = new javax.swing.JSpinner();
        jLabelNrFrom = new javax.swing.JLabel();
        jLabelNrTo = new javax.swing.JLabel();
        jSpinnerNrTo = new javax.swing.JSpinner();

        org.openide.awt.Mnemonics.setLocalizedText(jLabelName, java.util.ResourceBundle.getBundle("de/comicdb/comicdbcore/Bundle").getString("LBL_COMIC_NAME"));

        buttonGroup1.add(jRadioButtonMoreComic);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButtonMoreComic, java.util.ResourceBundle.getBundle("de/comicdb/comicdbcore/Bundle").getString("WIZ_Comic_MoreComic"));
        jRadioButtonMoreComic.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButtonMoreComic.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButtonMoreComic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMoreComicActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonOneComic);
        jRadioButtonOneComic.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButtonOneComic, java.util.ResourceBundle.getBundle("de/comicdb/comicdbcore/Bundle").getString("WIZ_Comic_OneComic"));
        jRadioButtonOneComic.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButtonOneComic.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButtonOneComic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOneComicActionPerformed(evt);
            }
        });

        jSpinnerNr.setModel(new SpinnerNumberModel(1, 1, Integer.MAX_VALUE, 1));

        org.openide.awt.Mnemonics.setLocalizedText(jLabelNr, java.util.ResourceBundle.getBundle("de/comicdb/comicdbcore/Bundle").getString("LBL_COMIC_NR"));

        jSpinnerNrFrom.setModel(new SpinnerNumberModel(1, 1, Integer.MAX_VALUE, 1));
        jSpinnerNrFrom.setEnabled(false);
        jSpinnerNrFrom.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerNrFromStateChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabelNrFrom, java.util.ResourceBundle.getBundle("de/comicdb/comicdbcore/Bundle").getString("WIZ_Comic_Nr_From"));

        org.openide.awt.Mnemonics.setLocalizedText(jLabelNrTo, java.util.ResourceBundle.getBundle("de/comicdb/comicdbcore/Bundle").getString("WIZ_Comic_Nr_To"));

        jSpinnerNrTo.setModel(new SpinnerNumberModel(1, 1, Integer.MAX_VALUE, 1));
        jSpinnerNrTo.setEnabled(false);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabelName)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextFieldName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
                    .add(jRadioButtonMoreComic)
                    .add(layout.createSequentialGroup()
                        .add(17, 17, 17)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(layout.createSequentialGroup()
                                .add(jLabelNrFrom)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jSpinnerNrFrom))
                            .add(layout.createSequentialGroup()
                                .add(jLabelNr)
                                .add(28, 28, 28)
                                .add(jSpinnerNr, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 25, Short.MAX_VALUE)
                        .add(jLabelNrTo)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jSpinnerNrTo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 84, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(95, 95, 95))
                    .add(jRadioButtonOneComic))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelName)
                    .add(jTextFieldName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(14, 14, 14)
                .add(jRadioButtonOneComic)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelNr)
                    .add(jSpinnerNr, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(19, 19, 19)
                .add(jRadioButtonMoreComic)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelNrFrom)
                    .add(jSpinnerNrFrom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelNrTo)
                    .add(jSpinnerNrTo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void jSpinnerNrFromStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerNrFromStateChanged
//        int min = ((SpinnerNumberModel)jSpinnerNrFrom.getModel()).getNumber().intValue();
        int min = ((Integer)jSpinnerNrFrom.getValue()).intValue();
        int value = ((SpinnerNumberModel)jSpinnerNrTo.getModel()).getNumber().intValue();
        if (min > value)
            value = min;
//        jSpinnerNrTo.setModel(new SpinnerNumberModel(min, value, Integer.MAX_VALUE, 1));
        ((SpinnerNumberModel)jSpinnerNrTo.getModel()).setValue(new Integer(value));
        ((SpinnerNumberModel)jSpinnerNrTo.getModel()).setMinimum(new Integer(min));
    }//GEN-LAST:event_jSpinnerNrFromStateChanged
    
    private void jRadioButtonMoreComicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMoreComicActionPerformed
        jSpinnerNr.setEnabled(!jRadioButtonMoreComic.isEnabled());
        jSpinnerNrFrom.setEnabled(jRadioButtonMoreComic.isEnabled());
        jSpinnerNrTo.setEnabled(jRadioButtonMoreComic.isEnabled());
    }//GEN-LAST:event_jRadioButtonMoreComicActionPerformed
    
    private void jRadioButtonOneComicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOneComicActionPerformed
        jSpinnerNr.setEnabled(jRadioButtonOneComic.isEnabled());
        jSpinnerNrFrom.setEnabled(!jRadioButtonOneComic.isEnabled());
        jSpinnerNrTo.setEnabled(!jRadioButtonOneComic.isEnabled());
    }//GEN-LAST:event_jRadioButtonOneComicActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNr;
    private javax.swing.JLabel jLabelNrFrom;
    private javax.swing.JLabel jLabelNrTo;
    private javax.swing.JRadioButton jRadioButtonMoreComic;
    private javax.swing.JRadioButton jRadioButtonOneComic;
    private javax.swing.JSpinner jSpinnerNr;
    private javax.swing.JSpinner jSpinnerNrFrom;
    private javax.swing.JSpinner jSpinnerNrTo;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
    
}

